# See: https://taskfile.dev/api/

version: "3"

tasks:
  generate:
    aliases:
      - gen
    desc: "Generate code from proto files"
    cmds:
      - protoc -I proto proto/auth_svc/*.proto --go_out=./gen/go/ --go_opt=paths=source_relative --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative
      - .\\env\\Scripts\\python -m grpc_tools.protoc -I proto proto/auth_svc/*.proto --python_out=./gen/py/ --pyi_out=./gen/py/ --grpc_python_out=./gen/py/